### PR TITLE
Updated video_player version in pubspec.yaml

### PR DESCRIPTION
**Pull request by morr0ne**
Related  #370 
This shouldn't cause any breaking changes as video_player already reached a stable api

### CODE REVIEW

**Comment by yy1300326388** [comment]
Upgrading Flutter v1.22.1 urgently needs this update

**Review by YazeedAlKhalaf — APPROVED** [review]
LGTM

**Review by fabiomcarneiro — APPROVED** [review]

**Comment by ganlanshu0211** [comment]
use 

> dependency_overrides:
>   video_player: ^0.11.1+2

in pubspec.yaml solve the problem

**Comment by Ahmadre** [comment]
As of the merge conflicts, I resolved this and will publish a new version ob pub soon.

**Pull request closed without merging**
