### PR TITLE
Adds the possibility to set on full screen preferred orientations

### PR DESCRIPTION
**Pull request by miguelpruivo**
Currently developers are restricted to use landscape right or left when in full screen while using an Android device, whereas in iOS it will adapt automatically. This will result in an odd behavior when playing portrait (aspect ratio 9:16 for example) videos.

This will add the `deviceOrientationsOnFullScreen` property that accepts a `List<Orientation>` for full screen playback that will be used for both platforms. If not provided, it will use de default landscape right/left for Android, as it is.

### CODE REVIEW

**Comment by miguelpruivo** [comment]
@brianegan regarding the comment in #225 about the `Hero` widget, as a suggestion, it would be great if the `Hero` could be optionally enabled instead of removing at all.

**Comment by Ahmadre** [comment]
@miguelpruivo applied your wishes in this PR: https://github.com/brianegan/chewie/pull/289 like @brianegan wanted to be in that PR. Please follow that PR for onEnterFullScreen :)

**Comment by miguelpruivo** [comment]
That's great news @Ahmadre, thank you!

**Comment by alexxlagutin** [comment]
Is there any information when this PR will be merged?

**Comment by Ahmadre** [comment]
@miguelpruivo @alexxlagutin Since version 0.10.x it's possible :) a big pr and many other changes came in 🥳

**Pull request closed without merging**
