### PR TITLE
AndroidX Migration, Video Player version updated in example

### PR DESCRIPTION
**Pull request by trademunch**
Upgraded Android compile and target SDK to 29 to make the current Example work.

Latest dependency of video player updated and auto rotation updated

Fixed example to make it to running condition

### CODE REVIEW

**Comment by Ahmadre** [comment]
Example is now fixed in this PR: https://github.com/brianegan/chewie/pull/289

Please follow that PR for updates 👍

**Comment by Ahmadre** [comment]
AndroidX possible now on version >=0.10.0 :)

**Comment by Ahmadre** [comment]
@trademunch a new version is up and android is fixed by @nstrelow . Can we close this PR?

**Comment by nstrelow** [comment]
Ahh missed this PR.
Updated the android project and will update the dependencies too.

Thanks alot @trademunch and sorry for overlooking this PR.

**Pull request closed without merging**
