### PR TITLE
Update to video_player >=0.7.0 <0.8.0

### PR DESCRIPTION
**Pull request by Sub6Resources**
An updated version of video_player was released on Oct. 17 with some bug fixes. I have upgraded Chewie to support this latest version.

### CODE REVIEW

**Comment by pepie** [comment]
Hello. Any update on where this will be released?
I am getting the same error.
Thanks

**Comment by brianegan** [comment]
Thanks for the update! My apologies on the delay -- been a busy travel & work week for me. I'll try to review and publish in the next day or so.

**Comment by brianegan** [comment]
Thanks! I've just merged this up. I'll do a few tests to make sure the new version works without any breaking changes.

**Comment by brianegan** [comment]
Published as part of `0.8.0`. Thanks again!

**Pull request merged**
