### PR TITLE
Show replay button if video completes for Android OS

### PR DESCRIPTION
**Pull request by manikandn**
Closes: #88

### CODE REVIEW

**Comment by nstrelow** [comment]
Hey thanks for the PR. Very on the point change.
If I am seeing this correctly, your PR changes the Icon when the video is finished.

The Issue you linked asked to reset the video to the beginning. Can you implement that as well?
And it would be great to also have the same for iOS. Maybe you can provide the code and somebody else can test it, if you do not have a Mac machine?

**Comment by nstrelow** [comment]
Upgraded the branch to newest chewie

**Comment by Ahmadre** [comment]
@manikandn for the Full implementation you can have a look here:

Material: lib/src/material_controls.dart

There's also an AnimatedIcon for Play/Pause. It would be great if we can also have this, but it's optional. The replay function is more important here 👍🏼

**Comment by manikandn** [comment]
@nstrelow Required changes are done and also tested in iOS as well. Please have a look.

@Ahmadre Thanks for the suggestion.

**Comment by Ahmadre** [comment]
New version is online: [Version](https://pub.dev/packages/chewie)

**Pull request merged**
