### PR TITLE
[WIP] Crop to aspect ratio

### PR DESCRIPTION
**Pull request by cbenhagen**
As is, this would be a breaking change that automatically gets the aspect ratio when ready and use the current `AspectRatio` set in the `ChewieController` to crop the video. This is useful to crop letterboxes for example.

### CODE REVIEW

**Comment by Ahmadre** [comment]
@cbenhagen when is this going to be merged?

**Comment by AndroidNils** [comment]
That pr would help's me a lot!

**Comment by Ahmadre** [comment]
@AndroidNils fixed AspectRatio, take a look here: https://github.com/brianegan/chewie/pull/289

**Comment by brianegan** [comment]
Thanks so much :)

This is a tricky one, and had discussion with @Ahmadre and others on a different channel.  #289 seems to fix the issue for folks! Closing in favor of that one.

**Comment by cbenhagen** [comment]
@brianegan https://github.com/brianegan/chewie/pull/289 does not seem to allow cropping a video. For example if you want to remove the letterboxes from a video.

**Comment by Ahmadre** [comment]
@cbenhagen Sure! We definetly should also have a cropping functionality in chewie. Maybe as an option?

**Pull request closed without merging**
