### PR TITLE
Bump required Flutter version 1.20 -> 1.22

### PR DESCRIPTION
**Pull request by daohoangson**
Since https://github.com/brianegan/chewie/commit/971c97aebaa976e3fd614426becc144d80d5f97a, chewie won't compile with Flutter version lower than 1.22. See https://github.com/flutter/flutter/commit/2032a448edd0da6460250f7d099d324a5989957f for more information. This commit bumps the required version in `pubspec.yaml` so app developers can upgrade their Flutter installation.

### CODE REVIEW

**Comment by Ahmadre** [comment]
> Since https://github.com/brianegan/chewie/commit/971c97aebaa976e3fd614426becc144d80d5f97a, chewie won't compile with Flutter version lower than 1.22. See https://github.com/flutter/flutter/commit/2032a448edd0da6460250f7d099d324a5989957f for more information. This commit bumps the required version in `pubspec.yaml` so app developers can upgrade their Flutter installation.

Could you please fix the Lint errors? The checks must pass, then we can merge this :). Thanks

**Comment by nstrelow** [comment]
> > Since [971c97a](https://github.com/brianegan/chewie/commit/971c97aebaa976e3fd614426becc144d80d5f97a), chewie won't compile with Flutter version lower than 1.22. See [flutter/flutter@2032a44](https://github.com/flutter/flutter/commit/2032a448edd0da6460250f7d099d324a5989957f) for more information. This commit bumps the required version in `pubspec.yaml` so app developers can upgrade their Flutter installation.
> 
> Could you please fix the Lint errors? The checks must pass, then we can merge this :). Thanks

@Ahmadre The lint issues were caused by a previous PR. I will fix them shortly.
Would be unfair to have the @daohoangson fix lint errors of others

**Comment by Ahmadre** [comment]
> > > Since [971c97a](https://github.com/brianegan/chewie/commit/971c97aebaa976e3fd614426becc144d80d5f97a), chewie won't compile with Flutter version lower than 1.22. See [flutter/flutter@2032a44](https://github.com/flutter/flutter/commit/2032a448edd0da6460250f7d099d324a5989957f) for more information. This commit bumps the required version in `pubspec.yaml` so app developers can upgrade their Flutter installation.
> 
> > 
> 
> > Could you please fix the Lint errors? The checks must pass, then we can merge this :). Thanks
> 
> 
> 
> @Ahmadre The lint issues were caused by a previous PR. I will fix them shortly.
> 
> Would be unfair to have the @daohoangson fix lint errors of others

Oh sure! Didn't encountered that, sorry for the quick merge on my side!

**Comment by daohoangson** [comment]
Thanks @nstrelow for the pointer, I was a bit surprised that a pubspec bump introduced a lint error. So is this PR good to merge now? I can fix the lint error in this PR too, if you want @Ahmadre.

**Comment by Ahmadre** [comment]
> Thanks @nstrelow for the pointer, I was a bit surprised that a pubspec bump introduced a lint error. So is this PR good to merge now? I can fix the lint error in this PR too, if you want @Ahmadre.

@nstrelow has already fixed this :) After the checks are done I'll merge this.

**Comment by nstrelow** [comment]
maeh we need to rebase first
I would merge now, it should be fine and if not, it's not this PRs fault

**Comment by daohoangson** [comment]
Ah you guys are fast. I have merged upstream into my branch. CI should be green now.

**Comment by Ahmadre** [comment]
> maeh we need to rebase first
> I would merge now, it should be fine and if not, it's not this PRs fault

haha yeah sure I wanted to rebase and update this branch, but he was faster XD hahaha

**Pull request merged**
